# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20170418_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('verification', models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Flagged'), (3, 'Declined')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Online'), (2, 'Offline'), (3, 'Removed')], default=0)),
                ('service_url', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('service_label', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('description', models.TextField(default=None, max_length=250)),
            ],
        ),
    ]
