# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='services',
            field=models.ManyToManyField(blank=True, to='registry.Services'),
        ),
    ]
