# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0002_palette_registry'),
        ('registry', '0004_registry_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='palette.Element'),
        ),
    ]
