# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0003_remove_palette_registry'),
        ('registry', '0005_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='palette',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='palette.Palette'),
        ),
    ]
