# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_registry_palette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='services',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
