# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20170424_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='mission',
            field=models.TextField(default=None, max_length=250, null=True),
        ),
    ]
