# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_auto_20170424_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='mission_why',
            field=models.TextField(default=None, max_length=250, null=True),
        ),
    ]
