# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_registry_mission_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='mission',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='mission_why',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
