# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_auto_20170527_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='primary_contact',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], default=0, null=True),
        ),
    ]
