# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_contact_primary_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='primary_contact',
        ),
    ]
