# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circle', '0008_auto_20170319_0246'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, default=None, max_length=140)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge_question', models.CharField(max_length=140)),
                ('challenge_answer', models.CharField(max_length=140)),
                ('content', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='circle.Content')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='circle.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('relationship', models.IntegerField(choices=[(0, 'Owner'), (1, 'Buddy')], default=0)),
                ('reason', models.CharField(blank=True, default=None, max_length=140)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='circle.Style')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='pact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pact.Pact'),
        ),
    ]
