# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='pact',
        ),
        migrations.RemoveField(
            model_name='pact',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pact',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='pact',
            name='project',
        ),
        migrations.RemoveField(
            model_name='person',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='person',
            name='style',
        ),
        migrations.DeleteModel(
            name='Checkin',
        ),
        migrations.DeleteModel(
            name='Pact',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
