# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 00:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0001_initial'),
        ('palette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(0, 'Torus'), (1, 'Station'), (2, 'Probe'), (3, 'Lander'), (4, 'Mothership')], default=0)),
                ('verification', models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Flagged'), (3, 'Declined')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Online'), (2, 'Offline'), (3, 'Removed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(blank=True, max_length=21, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.CharField(blank=True, default=None, max_length=140)),
                ('description', models.TextField(blank=True, default=None, max_length=140)),
                ('contact', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Contact')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('icon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='palette.Element')),
                ('palette', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='palette.Palette')),
                ('registry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registry.Registry')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Online'), (2, 'Offline'), (3, 'Removed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of_circle', models.IntegerField(choices=[(0, 'Text'), (1, 'Challenge'), (2, 'Photo'), (3, 'Video')], default=0)),
                ('name', models.CharField(max_length=60)),
                ('tagline', models.CharField(default=None, max_length=140)),
                ('description', models.TextField(default=None, max_length=140)),
                ('question', models.TextField(default=None, max_length=140)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('icon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='palette.Element')),
                ('palette', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='palette.Palette')),
            ],
        ),
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(0, 'Torus'), (1, 'Station'), (2, 'Probe'), (3, 'Lander'), (4, 'Mothership')], default=3)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Online'), (2, 'Offline'), (3, 'Removed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of_guideline', models.IntegerField(choices=[(0, 'Example'), (1, 'Rule')], default=0)),
                ('text', models.CharField(max_length=300)),
                ('content', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='circle.Content')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registry.Registry')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.IntegerField(choices=[(0, 'Internal'), (1, 'External')], default=0)),
                ('verification', models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Flagged'), (3, 'Declined')], default=1)),
                ('name', models.CharField(max_length=21)),
                ('directional_question', models.CharField(blank=True, default='What would you like to do?', max_length=140, null=True)),
                ('circle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='circle.Circle')),
                ('parent', models.ManyToManyField(blank=True, default=None, related_name='parents', to='circle.Circle')),
                ('registry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registry.Registry')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Online'), (2, 'Offline'), (3, 'Removed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=60)),
                ('tagline', models.CharField(blank=True, default=None, max_length=140)),
                ('description', models.TextField(blank=True, default=None, max_length=140)),
                ('circle', models.ManyToManyField(blank=True, default=None, to='circle.Circle')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('icon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='palette.Element')),
                ('palette', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='palette.Palette')),
                ('registry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registry.Registry')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='circle.Project'),
        ),
        migrations.AddField(
            model_name='content',
            name='registry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registry.Registry'),
        ),
    ]
