# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='directional_question',
            field=models.CharField(blank=True, default='What would you like to do?', max_length=140, null=True),
        ),
    ]
