# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0003_auto_20170410_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Torus'), (1, 'Station'), (2, 'Probe'), (3, 'Lander'), (4, 'Mothership')], default=0),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Torus'), (1, 'Station'), (2, 'Probe'), (3, 'Lander'), (4, 'Mothership')], default=3),
        ),
    ]
