# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0004_auto_20170420_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='parent',
            new_name='options',
        ),
    ]
