# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0005_auto_20170420_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='tagline',
            field=models.CharField(blank=True, default=None, max_length=140, null=True),
        ),
    ]
