# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0006_auto_20170424_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='tag',
        ),
        migrations.AlterField(
            model_name='circle',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=140, null=True),
        ),
    ]
