# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0007_auto_20170424_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=21, null=True),
        ),
    ]
