# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0007_auto_20170319_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='question',
            field=models.TextField(default=None, max_length=140),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
