# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0008_auto_20170424_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='circle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='circle.Circle'),
        ),
    ]
