# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0009_auto_20170424_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='group',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Offering'), (2, 'Need')], default=0),
        ),
    ]
