# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0010_circle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='purpose',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Add Registry')], default=0),
        ),
    ]
