# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0011_circle_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='purpose',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Add Registry'), (2, 'Add Offering'), (3, 'Add User')], default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='type_of_circle',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'Challenge'), (2, 'Photo'), (3, 'Video'), (4, 'Buy')], default=0),
        ),
    ]
