# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0013_auto_20170429_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideline',
            name='rank',
        ),
    ]
