# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0014_remove_guideline_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideline',
            name='content',
        ),
    ]
