# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0015_remove_guideline_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='offering_type',
            field=models.IntegerField(choices=[(0, 'Commit to'), (2, 'Learn about'), (3, 'Reminder to')], default=0),
        ),
    ]
