# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0016_circle_offering_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circle',
            name='offering_type',
        ),
    ]
