# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0017_remove_circle_offering_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='group',
            field=models.IntegerField(blank=True, choices=[(0, 'User'), (1, 'Offering'), (2, 'Need')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='purpose',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Add Registry'), (2, 'Add Offering'), (3, 'Add User')], default=0, null=True),
        ),
    ]
