# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0018_auto_20170430_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circle',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='circle',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circle',
            name='group',
            field=models.IntegerField(blank=True, choices=[(0, 'User'), (1, 'Offering'), (2, 'Need'), (3, 'Filter')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='purpose',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Add Registry'), (2, 'Add Offering'), (3, 'Add User'), (4, 'Add Filter')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='purpose',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Add Registry'), (2, 'Add Offering'), (3, 'Add User'), (4, 'Add Filter')], default=0),
        ),
    ]
