# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.IntegerField(choices=[(0, 'Icon'), (1, 'Width'), (2, 'CSS Property'), (3, 'Theme')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=140)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('background_color', models.CharField(max_length=7)),
                ('foreground_color', models.CharField(max_length=7)),
                ('accent_color_dark', models.CharField(max_length=7)),
                ('accent_color_light', models.CharField(max_length=7)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('element', models.ManyToManyField(blank=True, default=None, to='palette.Element')),
            ],
        ),
    ]
