# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.IntegerField(choices=[(0, 'Icon'), (1, 'Width'), (2, 'CSS Property'), (3, 'Theme')], default=0),
        ),
    ]
