# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0002_palette_registry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palette',
            name='registry',
        ),
    ]
