# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:17
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0003_remove_palette_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='accent_color_dark',
            field=colorful.fields.RGBColorField(),
        ),
        migrations.AlterField(
            model_name='palette',
            name='accent_color_light',
            field=colorful.fields.RGBColorField(),
        ),
        migrations.AlterField(
            model_name='palette',
            name='background_color',
            field=colorful.fields.RGBColorField(),
        ),
        migrations.AlterField(
            model_name='palette',
            name='foreground_color',
            field=colorful.fields.RGBColorField(),
        ),
    ]
