# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:17
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palette', '0004_auto_20170424_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='accent_color_dark',
            field=colorful.fields.RGBColorField(default='#4947c1'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='accent_color_light',
            field=colorful.fields.RGBColorField(default='#90caf9'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='background_color',
            field=colorful.fields.RGBColorField(default='#393a46'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='palette',
            name='foreground_color',
            field=colorful.fields.RGBColorField(default='##9fa8da'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
